### ISSUE TITLE
Merge Pre-Test Success Is Not Communicated Correctly

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/test-pull-requests#33]
When `test_pull_requests` is called with merge pre-test success on, and it evaluates a pull request that has successful tests, it posts a comment saying that there was a successful merge job, and links to the tests that succeeded before.

We should instead have a distinct message that says that a merge was successful due to the pre-test. We should not mislead people into thinking a merge job successfully ran.

**Comment by stevekuznetsov** [comment]
@bparees just hit this and was very confused

/cc @dobbymoodge @danmcp

**Comment by danmcp** [comment]
What would @bparees have done differently if he knew it was another merge job?  I don't like the idea of exposing this complexity to users.  The point of merge pretest success is that it was as good as a merge job.

Plus you can already see what it did because the two urls between the test and merge are the same.

**Comment by bparees** [comment]
@danmcp the part that was confusing was the implication that the bot used a merge job that predated my merge tag by 2 hours to merge my PR.  Which made me think something had gone awry in the bot (ie it had tested/merged the wrong thing).

I would have been happy if the bot had posted no additional comment/reference (then i would have probably understood it was pre-test merged)

**Comment by danmcp** [comment]
@bparees Meaning not post the comment indicated it had merged with a note of the build it was in?

**Comment by bparees** [comment]
@danmcp right.. https://github.com/openshift/origin/pull/10359#issuecomment-239918586

I think your point is that the bot is still telling you "it merged because it passed this test job" which is fair, but i read it as "it merged because, in response to your merge tag, i ran this job and it passed" which is not true and confusing.  Probably not confusing to most people or in most cases, but in this one, since i had literally just put the merge tag on the PR, it was disconcerting.

**Comment by danmcp** [comment]
@bparees You should have been happy!

**Comment by stevekuznetsov** [comment]
@danmcp yes as I said in the OP I think the biggest thing is:

> We should instead have a distinct message that says that a merge was successful due to the pre-test. We should not mislead people into thinking a merge job successfully ran.

**Comment by danmcp** [comment]
@stevekuznetsov Right, that I don't want to do.  The information is already there in the two links to the same tests and the whole point is that it has passed sufficient tests.  The bot contract isn't wait 10 hours and hope you merge.  It's merge when it's sufficiently passed the tests.  I think you have lowered your expectations too much :)

**Comment by bparees** [comment]
> @bparees You should have been happy!

@danmcp it's like you don't even know me at all...  when good things happen i get suspicious.

**Comment by stevekuznetsov** [comment]
@danmcp I disagree with your evaluation but it's not important enough to push it further. I'll just send the next person who gets confused to bump this page.

**Comment by danmcp** [comment]
@stevekuznetsov Just out of curiosity, you think printing a different message for this special case will confuse people less?

I don't think anyone has ever mentioned this being confusing so far.  Going on 4 years it's been there I think.

**Comment by stevekuznetsov** [comment]
Yes, I think a clear message that actually explains what happened instead of the quasi-English machine-generated machine-parsable text would confuse less. Anecdotally, I've explained that pretest success caused a weird-looking merge to four people recently, and even I got caught off guard by it when a merge job was kicked off and failed but the pretest merged the changes in before that.

**Comment by danmcp** [comment]
@stevekuznetsov 

> Yes, I think a clear message that actually explains what happened instead of the quasi-English machine-generated machine-parsable text would confuse less.

It's surprising to me you would say that given the backlash of the flake comments.

As far as the machine language:

continuous-integration/openshift-jenkins/merge SUCCESS (https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/7945/) (Image: devenv-rhel7_4837)

It just has four parts to it.  The first part is the only part that looks a little like machine language.  That string is actually in the config.  @smarterclayton I believe set it that way to make it look more like travis.

The other repos look like this:

Aggregated Logging Merge Results: SUCCESS (https://ci.openshift.redhat.com/jenkins/job/test-origin-aggregated-logging/703/)

But either way, it doesn't seem that bad to read.  I would personally rather not see a proper English sentence there.  I just want the information.  Not a sentence I have to parse the info out of.

**Comment by stevekuznetsov** [comment]
The sentence I would propose?

> Origin merge results: SUCCESS. Skipping merge tests as [passing tests](https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/7945/) exist.

Yes, as an organization maybe we've conditioned ourselves to read and understand the text that the bot spits out but I really don't think it is in any way better than an English sentence with the same amount of words. Maybe it doesn't make the most sense for us as an organization to move to a different message syntax since we're so invested in the old one ... but while that's a valid implementation nit I don't think it means that English is worse.
