### ISSUE TITLE
Merge Pre-Test Success Should Be Per-PR, not Per-Repo

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/test-pull-requests#34]
We should always only trigger a merge pre-test success on a single pull request to ensure that we do not accidentally apply it to other pull requests that are live at the same time.

**Comment by danmcp** [comment]
The intention of merge pretest success is to clear the queue.  And it still merges in order.  Breaking the order to pick particular pulls breaks the fairness rules.
