### ISSUE TITLE
Use Labels, Not Comments When Authorship Is Important

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/test-pull-requests#35]
Since comments are editable, this allows for an escalation of privileges when someone without merge rights has the rights to edit the comments of someone with merge rights to add the merge tag. If we use a label instead to trigger tests or merges and look to see that the label exists and the last person to apply it is trusted, we circumvent this issue as the GitHub issue events API can't be edited.

**Comment by danmcp** [comment]
@stevekuznetsov 

Is there an API to tell who added a label and at what time they added it?  Even if there is I think it has the following problems:

- Would be additional api calls
- It's not obvious how to ask for a remerge with a label

You can also setup your github repo to not have this problem if you have this concern.  Namely, don't give write access to the repo who don't also have [merge] access.

**Comment by stevekuznetsov** [comment]
> Is there an API to tell who added a label and at what time they added it? 

Yes, the issue events API.

> You can also setup your github repo to not have this problem if you have this concern. 

Sure, our org should look into it, then, if it's an issue.

**Comment by stevekuznetsov** [comment]
> It's not obvious how to ask for a remerge with a label

Bot could remove labels

**Comment by danmcp** [comment]
So I think my remaining concerns are:

- Would require additional api calls.  And it seems like a lot of them.
- This is only a partial solution given you would need a label for merge and test and testextended.  But you still wouldn't have a way to protect from which extended tests are picked.

**Comment by danmcp** [comment]
Also I am not sure removing labels works.  The bot currently attempts retest/remerge on additional commits from trusted PR users.

**Comment by stevekuznetsov** [comment]
> Would require additional api calls. And it seems like a lot of them.

No, we just get the list of events in addition to or in place of the list of comments.

> This is only a partial solution given you would need a label for merge and test and testextended.

Yes, instead of a comment for each we would need a label.

> But you still wouldn't have a way to protect from which extended tests are picked.

This is true, but that is not an escalation of privileges.

>  Also I am not sure removing labels works. The bot currently attempts retest/remerge on additional commits from trusted PR users.

I'm not certain what you mean -- removing a label is definitely something the bot could do. I'm not particularly interested in the impls here... but we could have the job trigger still be a comment but have as a prerequisite a label from a trusted user. I'm spit-balling here and don't really want to nit pick. We could also look upstream, since they use LGTM labels.

**Comment by danmcp** [comment]
> No, we just get the list of events in addition to or in place of the list of comments.

That's one additional call per pull.  That's a lot.

> This is true, but that is not an escalation of privileges.

It is a privilege to be able to ask for tests so it is an escalation.


> I'm not certain what you mean -- removing a label is definitely something the bot could do.

I thought you meant the merge label was necessary for a merge.  And the bot would remove the merge label after a failure so you would know you needed to readd it to get another test run.  I was saying this wouldn't work because the bot auto retests updates from trusted users.

I don't think the comment + label solves this.  If we remove the label, it still wouldn't retest by the rules.

> We could also look upstream, since they use LGTM labels.

I know upstream uses a lot more API calls than we do.  They also don't require a re[test] to retry from what I understand.
