### ISSUE TITLE
Forbidden error on invalid issue reference

### ISSUE THREAD

**Issue by danmcp** [openshift/test-pull-requests#40]
This comment

#27503 [test]

on 

https://github.com/openshift/origin/pull/11481

Caused this error:

    Investigating comment by screeley44: https://github.com/openshift/origin/pull/11481#issuecomment-255441167
      Determining if reference #27503 meets criteria...

    /usr/share/ruby/net/http/response.rb:119:in `error!': 403 "Forbidden" (Net::HTTPServerException)
	from /usr/bin/test_pull_requests:599:in `block in get_labels'
	from /usr/bin/test_pull_requests:591:in `each'
	from /usr/bin/test_pull_requests:591:in `get_labels'
	from /usr/bin/test_pull_requests:1399:in `issue_has_label?'
	from /usr/bin/test_pull_requests:1387:in `block in has_valid_issue_ref?'
	from /usr/bin/test_pull_requests:1384:in `scan'
	from /usr/bin/test_pull_requests:1384:in `has_valid_issue_ref?'
	from /usr/bin/test_pull_requests:1350:in `block in has_valid_flake_comment?'
	from /usr/bin/test_pull_requests:1337:in `each'
	from /usr/bin/test_pull_requests:1337:in `has_valid_flake_comment?'
	from /usr/bin/test_pull_requests:1650:in `block in process_pull_request'
	from /usr/bin/test_pull_requests:997:in `process_or_create_comment'
	from /usr/bin/test_pull_requests:1500:in `process_pull_request'
	from /usr/bin/test_pull_requests:2033:in `block in process_pull_requests'
	from /usr/bin/test_pull_requests:2024:in `each'
	from /usr/bin/test_pull_requests:2024:in `process_pull_requests'
	from /usr/bin/test_pull_requests:2310:in `<main>'

**Comment by dobbymoodge** [comment]
@danmcp unless I'm all turned around, this looks a lot like running up against the rate limit. Otherwise, it would be a permissions error, but that doesn't seem likely.

I'm on my phone so I can't take a closer look right now, will try to get to it sometime this weekend though.

**Comment by dobbymoodge** [comment]
Actually, probably an invalid URL...

**Comment by danmcp** [comment]
@dobbymoodge Correct.  It was an invalid url.
