### ISSUE TITLE
Support 301

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/test-pull-requests#55]
See:

```

+ /usr/bin/test_pull_requests --config /var/lib/jenkins/test_pull_requests/sti-wildfly.json
Rate limit remaining: 4478
Processing pull requests...

Processing repo 'sti-wildfly'
{"message":"Moved Permanently","url":"https://api.github.com/repositories/19788374/pulls?page=1&per_page=100","documentation_url":"https://developer.github.com/v3/#http-redirects"}
/usr/share/ruby/net/http/response.rb:119:in `error!': 301 "Moved Permanently" (Net::HTTPRetriableError)
	from /usr/bin/test_pull_requests:432:in `block in list_pull_requests'
	from /usr/bin/test_pull_requests:423:in `each'
	from /usr/bin/test_pull_requests:423:in `list_pull_requests'
	from /usr/bin/test_pull_requests:1994:in `block in process_pull_requests'
	from /usr/bin/test_pull_requests:1991:in `each'
	from /usr/bin/test_pull_requests:1991:in `process_pull_requests'
	from /usr/bin/test_pull_requests:2423:in `<main>'
```

/cc @dobbymoodge

**Comment by bparees** [comment]
yes please.

**Comment by stevekuznetsov** [comment]
We use the `get` method (?? it doesn't look like a method ... but I do not know enough ruby ... ) like [this](https://github.com/openshift/test-pull-requests/blob/master/test_pull_requests#L364) so I'd assume we would just need to update that ... but then also for the other verbs would we need to issue the request for the newer URL or would GitHub update? Might be easier to get `oct` etc. to handle non-openshift repos

**Comment by dobbymoodge** [comment]
Wait for #54 which will handle this the way the GitHub folks intended.

**Comment by dobbymoodge** [comment]
Also `perform_request` is the common method to handle all the http verbs,
and is where you'd wanna put the 301 handling. But pls don't because #54
kills it.

**Comment by dobbymoodge** [comment]
Just checked, we get this for free when we switch to Octokit: https://github.com/octokit/octokit.rb/blob/522f61863cc665e097fc1206dec1a1c2f7cd15ef/lib/octokit/middleware/follow_redirects.rb#L31
